# Generated by Django 5.0.7 on 2025-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryitem',
            options={'ordering': ['category', 'subcategory', 'name']},
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='category',
            field=models.CharField(choices=[('main-website', 'Main Website'), ('ecommerce', 'E-commerce'), ('blog', 'Blog'), ('portfolio', 'Portfolio'), ('landing-page', 'Landing Page'), ('dashboard', 'Dashboard')], default='main-website', max_length=50),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the template'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/previews/'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='subcategory',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('about-page', 'About Page'), ('contact-page', 'Contact Page'), ('services-page', 'Services Page'), ('pricing-page', 'Pricing Page'), ('domains-page', 'Domains Page'), ('product-listing', 'Product Listing'), ('product-detail', 'Product Detail'), ('shopping-cart', 'Shopping Cart'), ('checkout', 'Checkout'), ('blog-listing', 'Blog Listing'), ('blog-post', 'Blog Post'), ('author-page', 'Author Page'), ('gallery', 'Gallery'), ('project-detail', 'Project Detail'), ('lead-capture', 'Lead Capture'), ('product-launch', 'Product Launch'), ('event-landing', 'Event Landing'), ('analytics', 'Analytics'), ('user-management', 'User Management'), ('settings', 'Settings')], default='homepage', max_length=50),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='libraryitem',
            unique_together={('category', 'subcategory', 'name', 'target')},
        ),
    ]
