# Generated by Django 5.2.7 on 2025-10-30 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_alter_libraryitem_options_libraryitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('homepage', 'Homepage'), ('about', 'About'), ('services', 'Services'), ('contact', 'Contact'), ('portfolio', 'Portfolio')], default='homepage', max_length=50)),
                ('sections', models.JSONField(default=list, help_text='Template sections data')),
                ('preview', models.TextField(blank=True, help_text='Generated preview HTML')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='website_templates/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
